import Head from "next/head";
import estilos from "@/styles/Home.module.css";
//Importação dos componentes
import Topo from "@/Componentes/Topo";
import SecaoCapa from "@/Componentes/SecaoCapa";
import SecaoProdutos from "@/Componentes/SecaoProdutos";
import SecaoSobre from "@/Componentes/SecaoSobre";
import SecaoContatos from "@/Componentes/SecaoContatos";
import Rodape from "@/Componentes/Rodape";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topo/>
      <SecaoCapa/>
      <SecaoProdutos/>
      <SecaoSobre/>
      <SecaoContatos/>
      <Rodape/>
   
    </>
  );
}
